---
- name: Provision AWS instances
  hosts: localhost
  connection: local
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
  - group_vars/all

  tasks:
  - name: Launch AWS instances for jboss_demo
    ec2:
      #access_key: "{{ ec2_access_key }}"
      #secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ ec2_keypair }}"
      group: "{{ ec2_security_group }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      zone: "{{ ec2_zone }}"
      #vpc_id: "{{ ec2_vpc }}"
      vpc_subnet_id: "{{ ec2_subnet_id }}"
      instance_tags: "{'ansible_group':'jboss', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'{{ tower_user_name }}''_jboss_demo'}"
      count: "{{ ec2_instance_count }}"
      assign_public_ip: yes
      wait: true
    register: ec2_result

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22 
      delay: 60 
      timeout: 320 
      state: started
    with_items: "{{ ec2_result.instances }}"
    async: 250
    poll: 0
    register: wait_result

  - name: wait_for - check on async task
    async_status:
      jid: "{{ item.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 300
    with_items: "{{wait_result.results}}"

...
